openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/PVPMARTINS_1/PontusBackend2/1.0.0
  - url: http://localhost:8080/PontusTest/1.0.0
    description: SwaggerHub API Auto Mocking
  - url: http://localhost:8080/PontusTest/1.0.0
    description: SwaggerHub API Auto Mocking
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /menu/create:
    post:
      operationId: menuCreatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuCreateReq'
      responses:
        '201':
          description: Directory created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuCreateRes'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: MenuController
  /menu/read:
    post:
      operationId: menuReadPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuReadReq'

            # examples:
            #     Example 1:
            #       value:
            #         id: root
            #         name: Root
            #         type: folder
            #         path: /
      responses:
        '201':
          description: Directory created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuReadRes'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: MenuController
  /menu/update:
    post:
      operationId: menuUpdatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuUpdateReq'
      responses:
        '201':
          description: Directory updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuReadRes'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: MenuController
  /menu/delete:
    post:
      operationId: menuDeletePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuDeleteReq'
      responses:
        '201':
          description: Directory deleted successfully

        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: MenuController
  /table/create:
    post:
      summary: Create a new table
      description: Create a new table with properties and associated columns
      operationId: tableCreatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TableCreateReq'
            examples:
              example-0001:
                value:
                  name: Person Natural
                  cols:
                    - field: Person_Natural_Full_Name
                      filter: true
                      headerName: Full Name
                      id: Person_Natural_Full_Name
                      name: Full Name
                      sortable: true
                    - field: Person_Natural_Customer_ID
                      filter: true
                      headerName: Customer ID
                      id: Person_Natural_Customer_ID
                      name: Customer ID
                      sortable: true
      responses:
        '201':
          description: Table created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TableCreateRes'

        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: TableController
  /table/read:
    post:
      summary: Get table by id
      description: Get table by id
      operationId: tableReadPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TableReadReq'
            examples:
              example-0001:
                value:
                  id: mapeamentoDeProcessos
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TableReadRes'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: TableController
  /table/update:
    post:
      summary: Update table by ID
      description: Update table properties and associated columns by ID
      operationId: tableUpdatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TableUpdateReq'
        required: true
      responses:
        '204':
          description: Table updated successfully
        '400':
          description: Bad request
        '404':
          description: Table not found
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: TableController
  /table/delete:
    post:
      summary: Delete a table
      description: Delete a table by ID
      operationId: tableDeletePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TableDeleteReq'
        required: true
      responses:
        '204':
          description: Table deleted successfully
        '404':
          description: Table not found
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: TableController
  /tables/read:
    post:
      summary: Get all tables
      description: Retrieve all tables with pagination and search
      operationId: tablesReadPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadPaginationFilter'
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TablesReadRes'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: TableController
  /table/data/read:
    post:
      description: ''
      operationId: get-table-data
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/agGridReadReq'
            examples:
              example-0001:
                value:
                  dataType: Person_Natural
                  filters:
                    - colId: Person_Natural_Full_Name
                      condition1:
                        filter: JO
                        filterType: text
                        type: contains
                      condition2:
                        filter: SE
                        filterType: text
                        type: contains
                      filterType: text
                      operator: AND
                  from: 0
                  search:
                    cols:
                      - field: Person_Natural_Full_Name
                        filter: true
                        headerName: Full Name
                        id: Person_Natural_Full_Name
                        name: Full Name
                        sortable: true
                      - field: Person_Natural_Customer_ID
                        filter: true
                        headerName: Customer ID
                        id: Person_Natural_Customer_ID
                        name: Customer ID
                        sortable: true
                    extraSearch:
                      label: Person_Natural
                      value: Person_Natural
                    searchExact: true
                    searchStr: ''
                  sortCol: Person_Natural_Full_Name
                  sortDir: +asc
                  to: 100
      responses:
        '200':
          description: AG Record data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/agGridReadRes'
              examples:
                example-0001:
                  value:
                    type: recordReply
                    from: 0
                    records:
                      - "{\"Person_Natural_Customer_ID\":\"12345678999\",\"id\":\"#75:3817\"\
                        ,\"Person_Natural_Full_Name\":\"MARCO POLO\"}"
                      - "{\"Person_Natural_Customer_ID\":\"13333333333\",\"id\":\"#75:3911\"\
                        ,\"Person_Natural_Full_Name\":\"LEONARDO LOOPY\"}"
                    to: 2
                    totalAvailable: 4242
        '400':
          description: Invalid search supplied
        '401':
          description: Unauthorized
        '404':
          description: Person not found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal error
      x-swagger-router-controller: Default
  /table/data/create:
    post:
      summary: Create a new row
      description: 'Create a new row data, by using key/value pair for each column.'
      operationId: tableDataCreatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTableRow'
            examples:
              example-01:
                value:
                  id: mapeamentoDeProcessos
                  cols:
                    mapeamentoDeProcessoCol1: New value
                    mapeamentoDeProcessoCol2: New value
        required: true
      responses:
        '201':
          description: Table row created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /table/data/update:
    post:
      summary: Update a row
      description: 'Update a row data, by using key/value pair for each column.'
      operationId: tableDataUpdatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTableRow'
            examples:
              example-01:
                value:
                  id: mapeamentoDeProcessos
                  rowId: 15
                  cols:
                    mapeamentoDeProcessoCol1: Value Overwritten
                    mapeamentoDeProcessoCol2: Value Overwritten
        required: true
      responses:
        '201':
          description: Table row updated successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /table/data/delete:
    post:
      summary: Update a row
      description: 'Update a row data, by using key/value pair for each column.'
      operationId: tableDataDeletePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteTableRow'
            examples:
              example-01:
                value:
                  id: mapeamentoDeProcessos
                  rowId: 15
        required: true
      responses:
        '201':
          description: Table row deleted successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /dashboard/create:
    post:
      summary: Create a new dashboard
      description:
        "Create a new dashboard with properties, auth group, folder, and\
        \ owner"
      operationId: dashboardCreatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DashboardCreateReq'
        required: true
      responses:
        '201':
          description: Dashboard created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardCreateRes'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: DashboardController
  /dashboard/read:
    post:
      summary: Get dashboard by id
      description: Retrieve dashboard by id
      operationId: dashboardReadPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DashboardReadReq'
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardReadRes'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: DashboardController
  /dashboard/update:
    post:
      summary: Update dashboard by ID
      description:
        "Update dashboard properties, auth group, folder, and owner by\
        \ ID"
      operationId: dashboardUpdatePOST
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/DashboardUpdateReq'

        required: true
      responses:
        '204':
          description: Dashboard updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardUpdateRes'
        '400':
          description: Bad request
        '404':
          description: Dashboard not found
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: DashboardController
  /dashboard/delete:
    post:
      summary: Delete a dashboard
      description: Delete a dashboard by ID
      operationId: dashboardDeletePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DashboardDeleteReq'
        required: true
      responses:
        '204':
          description: Dashboard deleted successfully
        '404':
          description: Dashboard not found
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: DashboardController
  /dashboard/group/auth/create:
    post:
      summary: Create a new dashboard state
      description: Create a new dashboard state with name and state information
      operationId: dashboardGroupAuthCreatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_create_body'
        required: true
      responses:
        '201':
          description: Dashboard state created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardAuthGroup'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /dashboard/group/auth/read:
    post:
      summary: Create a new dashboard state
      description: Create a new dashboard state with name and state information
      operationId: dashboardGroupAuthReadPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_read_body'
        required: true
      responses:
        '201':
          description: Dashboard state created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardAuthGroup'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /dashboard/group/auth/update:
    post:
      summary: Create a new dashboard state
      description: Create a new dashboard state with name and state information
      operationId: dashboardGroupAuthUpdatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_update_body'
        required: true
      responses:
        '201':
          description: Dashboard state created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardAuthGroup'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /dashboard/group/auth/delete:
    post:
      summary: Delete group from dashboard
      description: Create a new dashboard state with name and state information
      operationId: dashboardGroupAuthDeletePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_delete_body'
        required: true
      responses:
        '201':
          description: Dashboard Auth Group(s) deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_delete_body'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /dashboards/read:
    post:
      summary: Get all dashboards
      description: Retrieve all dashboards with pagination and search
      operationId: dashboardsReadPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DashboardsReadReq'
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardsReadRes'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: DashboardController
  /auth/group/create:
    post:
      summary: Create a new group
      description: 'Create a new group with a name, parents, and symlinks'
      operationId: authGroupCreatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupCreateReq'
        required: true
      responses:
        '201':
          description: Group created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authGroupRef'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /auth/group/read:
    post:
      summary: Get group by ID
      description: Retrieve group by id
      operationId: authGroupReadPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/group_read_body'
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authGroupRef'
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /auth/group/update:
    post:
      summary: Update group by ID
      description: Update group details by ID
      operationId: authGroupUpdatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupUpdateReq'
        required: true
      responses:
        '204':
          description: Group updated successfully
        '400':
          description: Bad request
        '404':
          description: Group not found
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /auth/group/delete:
    post:
      summary: Delete a group
      description: Delete a group by ID
      operationId: authGroupDeletePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupDeleteReq'
        required: true
      responses:
        '204':
          description: Group deleted successfully
        '404':
          description: Group not found
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /auth/groups/read:
    post:
      summary: Get all groups
      description:
        Retrieve all groups (nodes that Aggrid is using a new pagination
        filter model)
      operationId: authGroupsReadPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadPaginationFilter'
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /auth/users/read:
    post:
      summary: Get all users
      description: Retrieve all users
      operationId: authUsersReadPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadPaginationFilter'
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /auth/user/create:
    post:
      summary: Create a new user
      description: Create a new user with a name and associated groups
      operationId: authUserCreatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
        required: true
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /auth/user/update:
    post:
      summary: Update user by ID
      description: Update user details by ID
      operationId: authUserUpdatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
        required: true
      responses:
        '204':
          description: User updated successfully
        '400':
          description: Bad request
        '404':
          description: User not found
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /auth/user/delete:
    post:
      summary: Delete a user
      description: Delete a user by ID
      operationId: authUserDeletePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteUser'
        required: true
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
  /auth/user/read:
    post:
      summary: Get user by ID
      description: Retrieve user by ID
      operationId: authUserReadPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_read_body'
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
      x-swagger-router-controller: Default
components:
  schemas:
    MenuCreateReq:
      allOf:
        - $ref: '#/components/schemas/MenuDirectoryTreeRef'
      # example:
      #   path: path
      #   children:
      #     - path: path
      #       children:
      #         - null
      #         - null
      #       name: name
      #       id: id
      #       type: type
      #     - path: path
      #       children:
      #         - null
      #         - null
      #       name: name
      #       id: id
      #       type: type
      #   name: name
      #   id: id
      #   type: type
    MenuCreateRes:
      allOf:
        - $ref: '#/components/schemas/MenuDirectoryTreeRef'
        - $ref: '#/components/schemas/BaseModelRef'
    MenuReadReq:
      allOf:
        - $ref: '#/components/schemas/BaseModelRef'
    MenuReadRes:
      allOf:
        - $ref: '#/components/schemas/MenuDirectoryTreeRef'
        - $ref: '#/components/schemas/BaseModelRef'
    MenuUpdateReq:
      allOf:
        - $ref: '#/components/schemas/MenuDirectoryTreeRef'
        - $ref: '#/components/schemas/BaseModelRef'
    MenuDeleteReq:
      allOf:
        - $ref: '#/components/schemas/BaseModelRef'
    MenuDirectoryTreeRef:
      type: object
      properties:
        name:
          type: string
        kind:
          type: string
        path:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/MenuDirectoryTreeRef'
      # example:
      #   path: path
      #   children:
      #     - null
      #     - null
      #   name: name
      #   type: type

    authGroupRef:
      type: object
      properties:
        groupId:
          type: string
          description: Unique identifier of the group
        name:
          type: string
          description: Name of the group
      example:
        groupId: groupId
        name: name
    GroupCreateReq:
      type: object
      properties:
        name:
          type: string
          description: Name of the group
        parents:
          type: array
          description: Parent groups of the group (optional)
          items:
            type: string
        symlinks:
          type: array
          description: Symlinks associated with the group (optional)
          items:
            type: string
    GroupUpdateReq:
      type: object
      properties:
        groupId:
          type: string
          description: ID of the group to update
        name:
          type: string
          description: Updated name of the group
        parents:
          type: array
          description: Updated parent groups of the group (optional)
          items:
            type: string
        symlinks:
          type: array
          description: Updated symlinks associated with the group (optional)
          items:
            type: string
    GroupDeleteReq:
      type: object
      properties:
        groupId:
          type: string
    agGridReadReq:
      type: object
      properties:
        search:
          $ref: '#/components/schemas/agGridInput_search'
        cols:
          type: array
          items:
            $ref: '#/components/schemas/agGridInput_search_cols'
        filters:
          type: array
          items:
            $ref: '#/components/schemas/agGridInput_filters'
        dataType:
          type: string
          example: Person_Natural
        from:
          type: number
          example: 0
        to:
          type: number
          example: 100
        sortCol:
          type: string
          example: Person_Natural_Customer_ID
        sortDir:
          type: string
          example: +desc
    agGridReadRes:
      type: object
      properties:
        type:
          type: string
        from:
          type: integer
          format: int32
        records:
          type: array
          items:
            type: string
        to:
          type: integer
          format: int32
        totalAvailable:
          type: integer
          format: int32
      example:
        totalAvailable: 1
        records:
          - records
          - records
        from: 0
        to: 6
        type: type
    TableColumnRef:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the table column
        name:
          type: string
          description: Name of the table column
        field:
          type: string
          description: Field name of the table column
        sortable:
          type: boolean
          description: Indicates if the table column is sortable
        headerName:
          type: string
          description: Header name of the table column
        filter:
          type: boolean
          description: Indicates if the table column is filterable
        kind:
          type: string
          enum:
            [
              checkboxes,
              selectbox,
              text,
              number,
              phone,
              zipcode,
              email,
              zipcode,
            ]
          description: Indicates the kind of column input
    TableRef:
      type: object
      properties:
        name:
          type: string
          description: Name of the table
        cols:
          type: array
          description: Table columns associated with the table
          items:
            $ref: '#/components/schemas/TableColumnRef'
      example:
        name: name
        id: id
        cols:
          - field: Person_Natural_Full_Name
            filter: true
            headerName: Full Name
            id: Person_Natural_Full_Name
            name: Full Name
            sortable: true
            kind: checkboxes
          - field: Person_Natural_Full_Name
            filter: true
            headerName: Full Name
            id: Person_Natural_Full_Name
            name: Full Name
            sortable: true
            kind: checkboxes
    TableReadRes:
      allOf:
        - $ref: '#/components/schemas/BaseModelRef'
        - $ref: '#/components/schemas/TableRef'
    TableCreateReq:
      type: object
      properties:
        name:
          type: string
          description: Name of the table
        cols:
          type: array
          description: Table columns to be associated with the table during creation
          items:
            $ref: '#/components/schemas/TableColumnRef'
    TableCreateRes:
      allOf:
        - $ref: '#/components/schemas/BaseModelRef'
        - $ref: '#/components/schemas/TableRef'
    TableDeleteReq:
      allOf:
        - $ref: '#/components/schemas/BaseModelRef'
    TableUpdateReq:
      allOf:
        - $ref: '#/components/schemas/BaseModelRef'
        - $ref: '#/components/schemas/TableRef'
    NewTableRow:
      type: object
      properties:
        id:
          type: string
        cols:
          $ref: '#/components/schemas/NewTableRow_cols'
    UpdateTableRow:
      type: object
      properties:
        id:
          type: string
        rowId:
          type: string
        cols:
          $ref: '#/components/schemas/NewTableRow_cols'
    DeleteTableRow:
      type: object
      properties:
        id:
          type: string
        rowId:
          type: string
    BaseModelRef:
      type: object
      properties:
        id:
          description: 'Unique identifier'
          type: string
      required:
        - id
    DashboardRef:
      type: object
      # additionalProperties: false
      properties:
        name:
          type: string
          description: Name of the dashboard
        folder:
          type: string
          description: Folder where the dashboard belongs
        owner:
          type: string
          description: Owner of the dashboard
        state:
          type: object
          description: JSON containing all the dashboard state
      example:
        owner: owner
        folder: folder
        name: name
        state: {}
    DashboardsReadReq:
      allOf:
        - $ref: '#/components/schemas/ReadPaginationFilter'

    DashboardReadReq:
      allOf:
        - $ref: '#/components/schemas/BaseModelRef'
    DashboardReadRes:
      allOf:
        - $ref: '#/components/schemas/DashboardRef'
        - $ref: '#/components/schemas/BaseModelRef'
    DashboardCreateReq:
      allOf:
        - $ref: '#/components/schemas/DashboardRef'
    DashboardCreateRes:
      allOf:
        - $ref: '#/components/schemas/DashboardRef'
        - $ref: '#/components/schemas/BaseModelRef'
    DashboardUpdateReq:
      type: object
      # unevaluatedProperties: false
      allOf:
        - $ref: '#/components/schemas/BaseModelRef'
        - $ref: '#/components/schemas/DashboardRef'
    DashboardUpdateRes:
      allOf:
        - $ref: '#/components/schemas/BaseModelRef'
        - $ref: '#/components/schemas/DashboardRef'
    DashboardDeleteReq:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseModelRef'
    AuthGroups:
      type: object
      properties:
        create:
          type: array
          items:
            type: string
        read:
          type: array
          items:
            type: string
        update:
          type: array
          items:
            type: string
        delete:
          type: array
          items:
            type: string
      example:
        read:
          - read
          - read
        create:
          - create
          - create
        update:
          - update
          - update
        delete:
          - delete
          - delete
    TableReadReq:
      allOf:
        - $ref: '#/components/schemas/BaseModelRef'

    ReadPaginationFilter:
      type: object
      additionalProperties: false
      properties:
        from:
          type: integer
        to:
          type: integer
        filters:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ReadPaginationFilter_filters'

    TablesReadRes:
      type: object
      properties:
        totalTables:
          type: integer
        tables:
          type: array
          description: Table columns associated with the table
          items:
            allOf:
              - $ref: '#/components/schemas/BaseModelRef'
              - $ref: '#/components/schemas/TableRef'
      example:
        tables:
          - name: name
            id: tableId
            cols:
              - filter: true
                headerName: headerName
                field: field
                name: name
                id: id
                sortable: true
              - filter: true
                headerName: headerName
                field: field
                name: name
                id: id
                sortable: true
          - name: name
            id: tableId
            cols:
              - filter: true
                headerName: headerName
                field: field
                name: name
                id: id
                sortable: true
              - filter: true
                headerName: headerName
                field: field
                name: name
                id: id
                sortable: true
        totalTables: 0
    User:
      type: object
      properties:
        userId:
          type: string
          description: Unique identifier of the user
        name:
          type: string
          description: Name of the user
        authGroups:
          type: array
          description: IDs of the groups the user belongs to
          items:
            type: string
      example:
        authGroups:
          - authGroups
          - authGroups
        name: name
        userId: userId
    NewUser:
      type: object
      properties:
        name:
          type: string
          description: Name of the user
        authGroups:
          type: array
          description: IDs of the groups the user belongs to
          items:
            type: string
    UpdateUser:
      type: object
      properties:
        userId:
          type: string
          description: ID of the user to update
        name:
          type: string
          description: Updated name of the user
        authGroups:
          type: array
          description: Updated IDs of the groups the user belongs to
          items:
            type: string
    DeleteUser:
      type: object
      properties:
        userId:
          type: string
    DashboardAuthGroup:
      type: object
      properties:
        dashboardId:
          type: string
          description: Unique identifier of the dashboard
        dashboardName:
          type: string
        authGroups:
          $ref: '#/components/schemas/AuthGroups'
      example:
        authGroups:
          read:
            - read
            - read
          create:
            - create
            - create
          update:
            - update
            - update
          delete:
            - delete
            - delete
        dashboardId: dashboardId
        dashboardName: dashboardName
    dashboardgroupauthcreate_authGroups:
      type: object
      properties:
        create:
          type: array
          items:
            type: string
        read:
          type: array
          items:
            type: string
        update:
          type: array
          items:
            type: string
        delete:
          type: array
          items:
            type: string
    auth_create_body:
      type: object
      properties:
        dashboardId:
          type: string
        authGroups:
          $ref: '#/components/schemas/dashboardgroupauthcreate_authGroups'
    auth_read_body:
      type: object
      properties:
        dashboardId:
          type: string
    auth_update_body:
      type: object
      properties:
        dashboardId:
          type: string
        authGroups:
          $ref: '#/components/schemas/AuthGroups'
    auth_delete_body:
      type: object
      properties:
        dashboardId:
          type: string
        authGroups:
          $ref: '#/components/schemas/AuthGroups'
      example:
        authGroups:
          read:
            - read
            - read
          create:
            - create
            - create
          update:
            - update
            - update
          delete:
            - delete
            - delete
        dashboardId: dashboardId
    DashboardsReadRes:
      type: object
      properties:
        totalDashboards:
          type: integer
        dashboards:
          type: array
          items:
            $ref: '#/components/schemas/Dashboard'
      example:
        totalDashboards: 0
        dashboards:
          - owner: owner
            folder: folder
            name: name
            id: id
          - owner: owner
            folder: folder
            name: name
            id: id
    group_read_body:
      type: object
      properties:
        groupId:
          type: string
    inline_response_200_1:
      type: object
      properties:
        totalGroups:
          type: integer
        authGroups:
          type: array
          items:
            $ref: '#/components/schemas/authGroupRef'
      example:
        authGroups:
          - groupId: groupId
            name: name
          - groupId: groupId
            name: name
        totalGroups: 0
    inline_response_200_2:
      type: object
      properties:
        totalUsers:
          type: integer
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
      example:
        totalUsers: 0
        users:
          - authGroups:
              - authGroups
              - authGroups
            name: name
            userId: userId
          - authGroups:
              - authGroups
              - authGroups
            name: name
            userId: userId
    user_read_body:
      type: object
      properties:
        userId:
          type: string
    agGridInput_search_cols:
      type: object
      properties:
        id:
          type: string
          example: Person_Natural_Full_Name
        name:
          type: string
          example: Full Name
        field:
          type: string
          example: Person_Natural_Full_Name
        sortable:
          type: boolean
        headerName:
          type: string
          example: Full Name
        filter:
          type: boolean
    agGridInput_search_extraSearch:
      type: object
      properties:
        label:
          type: string
          example: Person_Natural
        value:
          type: string
          example: Person_Natural
    agGridInput_search:
      type: object
      properties:
        searchStr:
          type: string
        searchExact:
          type: boolean
        cols:
          type: array
          items:
            $ref: '#/components/schemas/agGridInput_search_cols'
        extraSearch:
          $ref: '#/components/schemas/agGridInput_search_extraSearch'
    agGridInput_filters:
      type: object
      properties:
        colId:
          type: string
          example: Person_Natural_Full_Name
        filterType:
          type: string
          example: text
        type:
          type: string
          example: contains
        filter:
          type: string
          example: JO
    NewTableRow_cols:
      type: object
      properties:
        colId:
          type: string
    ReadPaginationFilter_filters_colId_condition:
      type: object
      properties:
        dateFrom:
          oneOf:
            - type: string
              format: date-time
            - type: string
        dateTo:
          oneOf:
            - type: string
              format: date-time
            - type: string
        filter:
          oneOf:
            - type: string
            - type: integer
        filterTo:
          oneOf:
            - type: string
            - type: integer
        filterType:
          type: string
        type:
          type: string

    ReadPaginationFilter_filters:
      type: object
      pattern: '^.+$'
      properties:
        sort:
          type: string
        filter:
          oneOf:
            - type: string
            - type: integer
        type:
          type: string
        dateFrom:
          oneOf:
            - type: string
              format: date-time
            - type: string
        dateTo:
          oneOf:
            - type: string
              format: date-time
            - type: string
        filterTo:
          oneOf:
            - type: string
            - type: integer
        condition1:
          $ref: '#/components/schemas/ReadPaginationFilter_filters_colId_condition'
        condition2:
          $ref: '#/components/schemas/ReadPaginationFilter_filters_colId_condition'
        filterType:
          type: string
        operator:
          type: string
    Dashboard:
      type: object
      properties:
        owner:
          type: string
        folder:
          type: string
        name:
          type: string
        id:
          type: string
      example:
        owner: owner
        folder: folder
        name: name
        id: id
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
